import React from 'react'
import Head from 'next/head'

export default function Helmet() {
    return (
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Yuriy Dvaranir</title>
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}